git-lfs

diff --git a/.config/git/hooks/post-commit b/.config/git/hooks/post-commit
--- a/.config/git/hooks/post-commit
+++ b/.config/git/hooks/post-commit
@@ -1,3 +1,6 @@
 #!/bin/sh
 
 echo "Created by $GIT_AUTHOR_NAME <$GIT_AUTHOR_EMAIL>\n"
+
+command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-commit' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
+git lfs post-commit "$@"
