git push threadholds

diff --git a/.config/git/hooks/pre-push b/.config/git/hooks/pre-push
--- a/.config/git/hooks/pre-push
+++ b/.config/git/hooks/pre-push
@@ -14,6 +14,24 @@ elapsed_time=$((current_time - last_my_commit_time))
 threadhold=60
 
 if [ $elapsed_time -lt $threadhold ]; then
-  echo "You have made a commit within the last $threadhold seconds. Please wait before pushing again."
-  exit 1
+
+  echo "You have made a commit within the last $threadhold seconds."
+
+  if test -t 0; then
+    echo "Do you want to push anyway? (y/N) "
+    read -r answer
+    case "$answer" in
+    [yY][eE][sS] | [yY])
+      echo "Proceeding with push..."
+      ;;
+    *)
+      echo "Push aborted."
+      exit 1
+      ;;
+    esac
+  else
+    echo "Please wait before pushing again."
+    exit 1
+  fi
+
 fi
